export interface Review {
  id: string;
  author: string;
  rating: number;
  date: string;
  content: string;
  likes: number;
}

export interface Course {
  id: string;
  name: string;
  englishName: string;
  credits: number;
  teacher: string;
  college: string;
  category: string;
  rating: number;
  students: number;
  tags: string[];
  features: string[];
  intro: string;
  outline: string[];
  assessment: string;
  cover: string;
  rank?: string;
  difficulty: "轻松" | "中等" | "挑战";
  reviews: Review[];
  isAlternate?: boolean;
}
export const CATEGORIES = ["全部", "通识教育必修课", "学科基础必修课", "专业核心必修课", "银行管理方向"];
const DEFAULT_REVIEWS: Review[] = [
  { id: "r1", author: "匿名同学 A", rating: 5, date: "2026-03-15", content: "内容比较贴近专业路径，适合按职业方向规划选课。", likes: 24 },
  { id: "r2", author: "2024级学生", rating: 4, date: "2026-02-10", content: "任务节奏清楚，提前看标签再选会更稳。", likes: 18 },
  { id: "r3", author: "修过这门的同学", rating: 4, date: "2026-01-05", content: "建议结合自己的基础课情况选择，实践课尤其要预留时间。", likes: 32 }
];
export const MOCK_COURSES: Course[] = [
  {
    id: "1",
    name: "大学英语（1-4）",
    englishName: "大学英语",
    credits: 8,
    teacher: "王老师",
    college: "通识教育学院",
    category: "通识教育必修课",
    rating: 4.2,
    students: 917,
    tags: ["英语基础", "跨学科融合", "闭卷", "理论"],
    features: ["跨学科融合"],
    difficulty: "轻松",
    assessment: "闭卷",
    intro: "大学英语（1-4）围绕通识教育能力展开，适合结合职业目标进行选择。课程标签包含英语基础、跨学科融合、闭卷。",
    outline: ["大学英语（1-4）基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "2",
    name: "计算机基础",
    englishName: "计算机基础",
    credits: 2,
    teacher: "李老师",
    college: "通识教育学院",
    category: "通识教育必修课",
    rating: 4.6,
    students: 1054,
    tags: ["闭卷", "理论"],
    features: ["闭卷", "理论"],
    difficulty: "轻松",
    assessment: "闭卷",
    intro: "计算机基础围绕通识教育能力展开，适合结合职业目标进行选择。课程标签包含闭卷、理论。",
    outline: ["计算机基础基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "3",
    name: "Python程序设计",
    englishName: "Python程序设计",
    credits: 3,
    teacher: "周老师",
    college: "通识教育学院",
    category: "通识教育必修课",
    rating: 4.2,
    students: 1191,
    tags: ["编程基础", "实操", "跨学科融合"],
    features: ["跨学科融合", "实操"],
    difficulty: "中等",
    assessment: "实操",
    intro: "Python程序设计围绕通识教育能力展开，适合结合职业目标进行选择。课程标签包含编程基础、实操、跨学科融合。",
    outline: ["Python程序设计基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "4",
    name: "军事理论",
    englishName: "军事理论",
    credits: 2,
    teacher: "赵老师",
    college: "通识教育学院",
    category: "通识教育必修课",
    rating: 4.7,
    students: 1328,
    tags: ["理论", "开卷", "闭卷"],
    features: ["理论", "开卷"],
    difficulty: "轻松",
    assessment: "开卷 + 闭卷",
    intro: "军事理论围绕通识教育能力展开，适合结合职业目标进行选择。课程标签包含理论、开卷、闭卷。",
    outline: ["军事理论基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "5",
    name: "大学生职业发展与就业指导",
    englishName: "大学生职业发展与就业指导",
    credits: 2,
    teacher: "林老师",
    college: "通识教育学院",
    category: "通识教育必修课",
    rating: 4.2,
    students: 1465,
    tags: ["随堂互动", "实操", "闭卷", "理论"],
    features: ["实操"],
    difficulty: "中等",
    assessment: "随堂互动 + 实操",
    intro: "大学生职业发展与就业指导围绕通识教育能力展开，适合结合职业目标进行选择。课程标签包含随堂互动、实操、闭卷。",
    outline: ["大学生职业发展与就业指导基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "6",
    name: "大学生创新创业教育",
    englishName: "大学生创新创业教育",
    credits: 2,
    teacher: "陈老师",
    college: "通识教育学院",
    category: "通识教育必修课",
    rating: 4.7,
    students: 1602,
    tags: ["小组报告", "随堂互动", "实操"],
    features: ["实操"],
    difficulty: "中等",
    assessment: "小组报告 + 随堂互动",
    intro: "大学生创新创业教育围绕通识教育能力展开，适合结合职业目标进行选择。课程标签包含小组报告、随堂互动、实操。",
    outline: ["大学生创新创业教育基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "7",
    name: "管理学",
    englishName: "管理学",
    credits: 2,
    teacher: "王老师",
    college: "通识教育学院",
    category: "通识教育必修课",
    rating: 4.3,
    students: 1739,
    tags: ["小组报告", "随堂互动", "实操"],
    features: ["实操"],
    difficulty: "中等",
    assessment: "小组报告 + 随堂互动",
    intro: "管理学围绕通识教育能力展开，适合结合职业目标进行选择。课程标签包含小组报告、随堂互动、实操。",
    outline: ["管理学基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "8",
    name: "经济法",
    englishName: "经济法",
    credits: 2,
    teacher: "李老师",
    college: "通识教育学院",
    category: "通识教育必修课",
    rating: 4.8,
    students: 1876,
    tags: ["论文", "闭卷", "理论"],
    features: ["论文", "闭卷"],
    difficulty: "轻松",
    assessment: "论文 + 闭卷",
    intro: "经济法围绕通识教育能力展开，适合结合职业目标进行选择。课程标签包含论文、闭卷、理论。",
    outline: ["经济法基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "9",
    name: "创新创业管理",
    englishName: "创新创业管理",
    credits: 2,
    teacher: "周老师",
    college: "通识教育学院",
    category: "通识教育必修课",
    rating: 4.3,
    students: 2013,
    tags: ["小组报告", "随堂互动", "实操", "热"],
    features: ["热", "实操"],
    difficulty: "中等",
    assessment: "小组报告 + 随堂互动",
    intro: "创新创业管理围绕通识教育能力展开，适合结合职业目标进行选择。课程标签包含小组报告、随堂互动、实操。",
    outline: ["创新创业管理基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "10",
    name: "政治经济学",
    englishName: "政治经济学",
    credits: 2,
    teacher: "赵老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.8,
    students: 2150,
    tags: ["理论", "闭卷", "热"],
    features: ["热"],
    difficulty: "轻松",
    assessment: "闭卷",
    intro: "政治经济学围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含理论、闭卷、热。",
    outline: ["政治经济学基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "11",
    name: "微观经济学",
    englishName: "微观经济学",
    credits: 2,
    teacher: "林老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.4,
    students: 2287,
    tags: ["理论", "闭卷", "热"],
    features: ["热"],
    difficulty: "轻松",
    assessment: "闭卷",
    intro: "微观经济学围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含理论、闭卷、热。",
    outline: ["微观经济学基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "12",
    name: "宏观经济学",
    englishName: "宏观经济学",
    credits: 2,
    teacher: "陈老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.8,
    students: 2424,
    tags: ["理论", "闭卷", "热"],
    features: ["热"],
    difficulty: "轻松",
    assessment: "闭卷",
    intro: "宏观经济学围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含理论、闭卷、热。",
    outline: ["宏观经济学基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "13",
    name: "计量经济学",
    englishName: "计量经济学",
    credits: 3,
    teacher: "王老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.4,
    students: 2561,
    tags: ["计量基础", "统计基础", "难", "热"],
    features: ["热", "难"],
    difficulty: "挑战",
    assessment: "课程任务 + 期末考核",
    intro: "计量经济学围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含计量基础、统计基础、难。",
    outline: ["计量经济学基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "14",
    name: "统计学",
    englishName: "统计学",
    credits: 3,
    teacher: "李老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.9,
    students: 2698,
    tags: ["计量基础", "统计基础", "难", "热"],
    features: ["热", "难"],
    difficulty: "挑战",
    assessment: "课程任务 + 期末考核",
    intro: "统计学围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含计量基础、统计基础、难。",
    outline: ["统计学基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "15",
    name: "会计学",
    englishName: "会计学",
    credits: 3,
    teacher: "周老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.5,
    students: 2835,
    tags: ["会计基础", "主修", "闭卷", "理论", "热"],
    features: ["热", "主修"],
    difficulty: "中等",
    assessment: "闭卷",
    intro: "会计学围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含会计基础、主修、闭卷。",
    outline: ["会计学基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "16",
    name: "财政学",
    englishName: "财政学",
    credits: 2,
    teacher: "赵老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.0,
    students: 2972,
    tags: ["理论", "闭卷", "热"],
    features: ["热"],
    difficulty: "轻松",
    assessment: "闭卷",
    intro: "财政学围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含理论、闭卷、热。",
    outline: ["财政学基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "17",
    name: "金融学（货币金融学）",
    englishName: "金融学 货币金融学",
    credits: 2,
    teacher: "林老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.9,
    students: 809,
    tags: ["闭卷", "理论"],
    features: ["闭卷", "理论"],
    difficulty: "轻松",
    assessment: "闭卷",
    intro: "金融学（货币金融学）围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含闭卷、理论。",
    outline: ["金融学（货币金融学）基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "18",
    name: "线性代数",
    englishName: "线性代数",
    credits: 3,
    teacher: "陈老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.5,
    students: 946,
    tags: ["线代基础", "理论", "闭卷"],
    features: ["线代基础", "理论"],
    difficulty: "轻松",
    assessment: "闭卷",
    intro: "线性代数围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含线代基础、理论、闭卷。",
    outline: ["线性代数基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "19",
    name: "微积分（高等数学）",
    englishName: "微积分 高等数学",
    credits: 6,
    teacher: "王老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.0,
    students: 1083,
    tags: ["高数基础", "理论", "难"],
    features: ["难"],
    difficulty: "挑战",
    assessment: "课程任务 + 期末考核",
    intro: "微积分（高等数学）围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含高数基础、理论、难。",
    outline: ["微积分（高等数学）基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "20",
    name: "概率论与数理统计",
    englishName: "概率论与数理统计",
    credits: 3,
    teacher: "李老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.5,
    students: 1220,
    tags: ["计量基础", "统计基础", "难"],
    features: ["难"],
    difficulty: "挑战",
    assessment: "课程任务 + 期末考核",
    intro: "概率论与数理统计围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含计量基础、统计基础、难。",
    outline: ["概率论与数理统计基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "21",
    name: "金融市场学",
    englishName: "金融市场学",
    credits: 2,
    teacher: "周老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.1,
    students: 1357,
    tags: ["闭卷", "理论"],
    features: ["闭卷", "理论"],
    difficulty: "轻松",
    assessment: "闭卷",
    intro: "金融市场学围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含闭卷、理论。",
    outline: ["金融市场学基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "22",
    name: "保险学原理",
    englishName: "保险学原理",
    credits: 2,
    teacher: "赵老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.5,
    students: 1494,
    tags: ["闭卷", "理论"],
    features: ["闭卷", "理论"],
    difficulty: "轻松",
    assessment: "闭卷",
    intro: "保险学原理围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含闭卷、理论。",
    outline: ["保险学原理基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "23",
    name: "中央银行学",
    englishName: "中央银行学",
    credits: 2,
    teacher: "林老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.1,
    students: 1631,
    tags: ["主修", "理论", "闭卷"],
    features: ["主修"],
    difficulty: "中等",
    assessment: "闭卷",
    intro: "中央银行学围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含主修、理论、闭卷。",
    outline: ["中央银行学基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1601597111158-2fceff292cdc?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "24",
    name: "国际结算",
    englishName: "国际结算",
    credits: 2,
    teacher: "陈老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.6,
    students: 1768,
    tags: ["英语基础", "跨学科融合", "闭卷", "理论"],
    features: ["跨学科融合"],
    difficulty: "轻松",
    assessment: "闭卷",
    intro: "国际结算围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含英语基础、跨学科融合、闭卷。",
    outline: ["国际结算基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "25",
    name: "信托与租赁",
    englishName: "信托与租赁",
    credits: 2,
    teacher: "王老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.2,
    students: 1905,
    tags: ["闭卷", "理论"],
    features: ["闭卷", "理论"],
    difficulty: "轻松",
    assessment: "闭卷",
    intro: "信托与租赁围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含闭卷、理论。",
    outline: ["信托与租赁基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "26",
    name: "利息理论",
    englishName: "利息理论",
    credits: 2,
    teacher: "李老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.6,
    students: 2042,
    tags: ["闭卷", "理论", "热"],
    features: ["热"],
    difficulty: "轻松",
    assessment: "闭卷",
    intro: "利息理论围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含闭卷、理论、热。",
    outline: ["利息理论基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "27",
    name: "货币理论",
    englishName: "货币理论",
    credits: 2,
    teacher: "周老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.2,
    students: 2179,
    tags: ["理论", "闭卷", "热"],
    features: ["热"],
    difficulty: "轻松",
    assessment: "闭卷",
    intro: "货币理论围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含理论、闭卷、热。",
    outline: ["货币理论基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "28",
    name: "金融工程",
    englishName: "金融工程",
    credits: 2,
    teacher: "赵老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.7,
    students: 2316,
    tags: ["金工基础", "难", "主修", "热"],
    features: ["热", "主修"],
    difficulty: "挑战",
    assessment: "课程任务 + 期末考核",
    intro: "金融工程围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含金工基础、难、主修。",
    outline: ["金融工程基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "29",
    name: "金融业会计",
    englishName: "金融业会计",
    credits: 3,
    teacher: "林老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.2,
    students: 2453,
    tags: ["会计基础", "主修", "闭卷", "理论", "热"],
    features: ["热", "主修"],
    difficulty: "中等",
    assessment: "闭卷",
    intro: "金融业会计围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含会计基础、主修、闭卷。",
    outline: ["金融业会计基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "30",
    name: "经济法",
    englishName: "经济法",
    credits: 2,
    teacher: "陈老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.7,
    students: 2590,
    tags: ["论文", "闭卷", "理论", "热"],
    features: ["热"],
    difficulty: "轻松",
    assessment: "论文 + 闭卷",
    intro: "经济法围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含论文、闭卷、理论。",
    outline: ["经济法基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "31",
    name: "管理学",
    englishName: "管理学",
    credits: 2,
    teacher: "王老师",
    college: "金融学院",
    category: "学科基础必修课",
    rating: 4.3,
    students: 2727,
    tags: ["小组报告", "随堂互动", "实操", "热"],
    features: ["热", "实操"],
    difficulty: "中等",
    assessment: "小组报告 + 随堂互动",
    intro: "管理学围绕学科基础能力展开，适合结合职业目标进行选择。课程标签包含小组报告、随堂互动、实操。",
    outline: ["管理学基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "32",
    name: "公司金融",
    englishName: "公司金融",
    credits: 3,
    teacher: "李老师",
    college: "金融学院",
    category: "专业核心必修课",
    rating: 4.7,
    students: 2864,
    tags: ["主修", "闭卷", "理论", "热"],
    features: ["热", "主修"],
    difficulty: "中等",
    assessment: "闭卷",
    intro: "公司金融围绕专业核心能力展开，适合结合职业目标进行选择。课程标签包含主修、闭卷、理论。",
    outline: ["公司金融基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "33",
    name: "证券投资学",
    englishName: "证券投资学",
    credits: 3,
    teacher: "周老师",
    college: "金融学院",
    category: "专业核心必修课",
    rating: 4.3,
    students: 3901,
    tags: ["热", "主修", "闭卷", "理论", "满"],
    features: ["热", "满"],
    difficulty: "中等",
    assessment: "闭卷",
    intro: "证券投资学围绕专业核心能力展开，适合结合职业目标进行选择。课程标签包含热、主修、闭卷。",
    outline: ["证券投资学基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "34",
    name: "国际金融",
    englishName: "国际金融",
    credits: 3,
    teacher: "赵老师",
    college: "金融学院",
    category: "专业核心必修课",
    rating: 4.3,
    students: 838,
    tags: ["英语基础", "跨学科融合", "主修"],
    features: ["主修", "跨学科融合"],
    difficulty: "中等",
    assessment: "课程任务 + 期末考核",
    intro: "国际金融围绕专业核心能力展开，适合结合职业目标进行选择。课程标签包含英语基础、跨学科融合、主修。",
    outline: ["国际金融基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "35",
    name: "商业银行业务与经营",
    englishName: "商业银行业务与经营",
    credits: 3,
    teacher: "林老师",
    college: "金融学院",
    category: "专业核心必修课",
    rating: 4.8,
    students: 975,
    tags: ["主修", "理论", "闭卷"],
    features: ["主修"],
    difficulty: "中等",
    assessment: "闭卷",
    intro: "商业银行业务与经营围绕专业核心能力展开，适合结合职业目标进行选择。课程标签包含主修、理论、闭卷。",
    outline: ["商业银行业务与经营基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1601597111158-2fceff292cdc?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "36",
    name: "金融风险管理",
    englishName: "金融风险管理",
    credits: 3,
    teacher: "陈老师",
    college: "金融学院",
    category: "专业核心必修课",
    rating: 4.3,
    students: 1112,
    tags: ["主修", "理论", "小组报告", "随堂互动", "实操"],
    features: ["主修", "实操"],
    difficulty: "中等",
    assessment: "小组报告 + 随堂互动",
    intro: "金融风险管理围绕专业核心能力展开，适合结合职业目标进行选择。课程标签包含主修、理论、小组报告。",
    outline: ["金融风险管理基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "37",
    name: "金融计量分析与应用",
    englishName: "金融计量分析与应用",
    credits: 3,
    teacher: "王老师",
    college: "金融学院",
    category: "专业核心必修课",
    rating: 4.8,
    students: 1249,
    tags: ["计量基础", "统计基础", "难", "主修"],
    features: ["主修", "难"],
    difficulty: "挑战",
    assessment: "课程任务 + 期末考核",
    intro: "金融计量分析与应用围绕专业核心能力展开，适合结合职业目标进行选择。课程标签包含计量基础、统计基础、难。",
    outline: ["金融计量分析与应用基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "38",
    name: "金融经济学",
    englishName: "金融经济学",
    credits: 3,
    teacher: "李老师",
    college: "金融学院",
    category: "专业核心必修课",
    rating: 4.4,
    students: 1386,
    tags: ["理论", "闭卷", "主修"],
    features: ["主修"],
    difficulty: "中等",
    assessment: "闭卷",
    intro: "金融经济学围绕专业核心能力展开，适合结合职业目标进行选择。课程标签包含理论、闭卷、主修。",
    outline: ["金融经济学基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "39",
    name: "投资银行学",
    englishName: "投资银行学",
    credits: 3,
    teacher: "周老师",
    college: "金融学院",
    category: "专业核心必修课",
    rating: 4.8,
    students: 2423,
    tags: ["热", "主修", "理论"],
    features: ["热", "主修"],
    difficulty: "中等",
    assessment: "课程任务 + 期末考核",
    intro: "投资银行学围绕专业核心能力展开，适合结合职业目标进行选择。课程标签包含热、主修、理论。",
    outline: ["投资银行学基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1601597111158-2fceff292cdc?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "40",
    name: "财务报告分析",
    englishName: "财务报告分析",
    credits: 3,
    teacher: "赵老师",
    college: "金融学院",
    category: "专业核心必修课",
    rating: 4.4,
    students: 1660,
    tags: ["会计基础", "主修", "闭卷", "理论"],
    features: ["主修"],
    difficulty: "中等",
    assessment: "闭卷",
    intro: "财务报告分析围绕专业核心能力展开，适合结合职业目标进行选择。课程标签包含会计基础、主修、闭卷。",
    outline: ["财务报告分析基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "41",
    name: "衍生金融工具",
    englishName: "衍生金融工具",
    credits: 3,
    teacher: "林老师",
    college: "金融学院",
    category: "专业核心必修课",
    rating: 4.9,
    students: 1797,
    tags: ["金工基础", "难", "主修"],
    features: ["主修", "难"],
    difficulty: "挑战",
    assessment: "课程任务 + 期末考核",
    intro: "衍生金融工具围绕专业核心能力展开，适合结合职业目标进行选择。课程标签包含金工基础、难、主修。",
    outline: ["衍生金融工具基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "42",
    name: "金融计量学",
    englishName: "金融计量学",
    credits: 3,
    teacher: "陈老师",
    college: "金融学院",
    category: "专业核心必修课",
    rating: 4.4,
    students: 1934,
    tags: ["计量基础", "统计基础", "难", "主修"],
    features: ["主修", "难"],
    difficulty: "挑战",
    assessment: "课程任务 + 期末考核",
    intro: "金融计量学围绕专业核心能力展开，适合结合职业目标进行选择。课程标签包含计量基础、统计基础、难。",
    outline: ["金融计量学基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "43",
    name: "数字金融（思维专题）",
    englishName: "数字金融 思维专题",
    credits: 2,
    teacher: "王老师",
    college: "金融学院",
    category: "专业核心必修课",
    rating: 4.0,
    students: 2071,
    tags: ["思维", "小组作业", "随堂互动", "跨学科融合", "主修"],
    features: ["主修", "跨学科融合"],
    difficulty: "中等",
    assessment: "小组作业 + 随堂互动",
    intro: "数字金融（思维专题）围绕专业核心能力展开，适合结合职业目标进行选择。课程标签包含思维、小组作业、随堂互动。",
    outline: ["数字金融（思维专题）基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "44",
    name: "数字金融（实操专题）",
    englishName: "数字金融 实操专题",
    credits: 3,
    teacher: "李老师",
    college: "金融学院",
    category: "专业核心必修课",
    rating: 4.5,
    students: 2208,
    tags: ["实操", "闭卷", "编程", "编程基础", "主修"],
    features: ["主修", "实操"],
    difficulty: "中等",
    assessment: "实操 + 闭卷",
    intro: "数字金融（实操专题）围绕专业核心能力展开，适合结合职业目标进行选择。课程标签包含实操、闭卷、编程。",
    outline: ["数字金融（实操专题）基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "45",
    name: "金融科技",
    englishName: "金融科技",
    credits: 3,
    teacher: "周老师",
    college: "金融学院",
    category: "专业核心必修课",
    rating: 4.0,
    students: 2345,
    tags: ["主修", "闭卷", "理论", "热"],
    features: ["热", "主修"],
    difficulty: "中等",
    assessment: "闭卷",
    intro: "金融科技围绕专业核心能力展开，适合结合职业目标进行选择。课程标签包含主修、闭卷、理论。",
    outline: ["金融科技基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "46",
    name: "商业银行信贷管理",
    englishName: "商业银行信贷管理",
    credits: 2,
    teacher: "赵老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.5,
    students: 2482,
    tags: ["主修", "理论", "小组报告", "随堂互动", "实操"],
    features: ["主修", "实操"],
    difficulty: "中等",
    assessment: "小组报告 + 随堂互动",
    intro: "商业银行信贷管理围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含主修、理论、小组报告。",
    outline: ["商业银行信贷管理基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1601597111158-2fceff292cdc?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "47",
    name: "银行会计",
    englishName: "银行会计",
    credits: 3,
    teacher: "林老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.1,
    students: 2619,
    tags: ["会计基础", "主修", "理论", "热"],
    features: ["热", "主修"],
    difficulty: "中等",
    assessment: "课程任务 + 期末考核",
    intro: "银行会计围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含会计基础、主修、理论。",
    outline: ["银行会计基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1601597111158-2fceff292cdc?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "48",
    name: "国际银行业务",
    englishName: "国际银行业务",
    credits: 2,
    teacher: "陈老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.6,
    students: 2756,
    tags: ["英语基础", "跨学科融合", "主修", "理论", "热"],
    features: ["热", "主修"],
    difficulty: "中等",
    assessment: "课程任务 + 期末考核",
    intro: "国际银行业务围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含英语基础、跨学科融合、主修。",
    outline: ["国际银行业务基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1601597111158-2fceff292cdc?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "49",
    name: "银行风险管理",
    englishName: "银行风险管理",
    credits: 2,
    teacher: "王老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.1,
    students: 2893,
    tags: ["主修", "理论", "小组报告", "随堂互动", "实操"],
    features: ["主修", "实操"],
    difficulty: "中等",
    assessment: "小组报告 + 随堂互动",
    intro: "银行风险管理围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含主修、理论、小组报告。",
    outline: ["银行风险管理基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1601597111158-2fceff292cdc?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "50",
    name: "金融监管学",
    englishName: "金融监管学",
    credits: 2,
    teacher: "李老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.6,
    students: 3030,
    tags: ["主修", "理论", "闭卷", "热"],
    features: ["热", "主修"],
    difficulty: "中等",
    assessment: "闭卷",
    intro: "金融监管学围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含主修、理论、闭卷。",
    outline: ["金融监管学基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1601597111158-2fceff292cdc?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "51",
    name: "固定收益证券",
    englishName: "固定收益证券",
    credits: 2,
    teacher: "周老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.6,
    students: 1767,
    tags: ["热", "主修", "闭卷", "理论"],
    features: ["热", "主修"],
    difficulty: "中等",
    assessment: "闭卷",
    intro: "固定收益证券围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含热、主修、闭卷。",
    outline: ["固定收益证券基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "52",
    name: "权益投资",
    englishName: "权益投资",
    credits: 2,
    teacher: "赵老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.1,
    students: 1904,
    tags: ["热", "主修", "闭卷", "理论"],
    features: ["热", "主修"],
    difficulty: "中等",
    assessment: "闭卷",
    intro: "权益投资围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含热、主修、闭卷。",
    outline: ["权益投资基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "53",
    name: "投资组合管理",
    englishName: "投资组合管理",
    credits: 2,
    teacher: "林老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.6,
    students: 2041,
    tags: ["热", "主修", "小组报告", "随堂互动", "实操"],
    features: ["热", "主修"],
    difficulty: "中等",
    assessment: "小组报告 + 随堂互动",
    intro: "投资组合管理围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含热、主修、小组报告。",
    outline: ["投资组合管理基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "54",
    name: "个人理财",
    englishName: "个人理财",
    credits: 2,
    teacher: "陈老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.2,
    students: 1278,
    tags: ["主修", "闭卷", "理论"],
    features: ["主修"],
    difficulty: "中等",
    assessment: "闭卷",
    intro: "个人理财围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含主修、闭卷、理论。",
    outline: ["个人理财基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "55",
    name: "基金管理",
    englishName: "基金管理",
    credits: 2,
    teacher: "王老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.7,
    students: 2315,
    tags: ["热", "主修", "小组报告", "随堂互动", "实操"],
    features: ["热", "主修"],
    difficulty: "中等",
    assessment: "小组报告 + 随堂互动",
    intro: "基金管理围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含热、主修、小组报告。",
    outline: ["基金管理基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "56",
    name: "期货与期权",
    englishName: "期货与期权",
    credits: 2,
    teacher: "李老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.2,
    students: 1552,
    tags: ["金工基础", "难", "主修"],
    features: ["主修", "难"],
    difficulty: "挑战",
    assessment: "课程任务 + 期末考核",
    intro: "期货与期权围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含金工基础、难、主修。",
    outline: ["期货与期权基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "57",
    name: "国际金融市场",
    englishName: "国际金融市场",
    credits: 2,
    teacher: "周老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.7,
    students: 1689,
    tags: ["英语基础", "跨学科融合", "主修"],
    features: ["主修", "跨学科融合"],
    difficulty: "中等",
    assessment: "课程任务 + 期末考核",
    intro: "国际金融市场围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含英语基础、跨学科融合、主修。",
    outline: ["国际金融市场基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "58",
    name: "跨国公司金融",
    englishName: "跨国公司金融",
    credits: 2,
    teacher: "赵老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.3,
    students: 1826,
    tags: ["英语基础", "跨学科融合", "主修"],
    features: ["主修", "跨学科融合"],
    difficulty: "中等",
    assessment: "课程任务 + 期末考核",
    intro: "跨国公司金融围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含英语基础、跨学科融合、主修。",
    outline: ["跨国公司金融基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "59",
    name: "国际投资学",
    englishName: "国际投资学",
    credits: 2,
    teacher: "林老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.7,
    students: 2863,
    tags: ["英语基础", "跨学科融合", "热", "主修"],
    features: ["热", "主修"],
    difficulty: "中等",
    assessment: "课程任务 + 期末考核",
    intro: "国际投资学围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含英语基础、跨学科融合、热。",
    outline: ["国际投资学基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "60",
    name: "外汇业务与管理",
    englishName: "外汇业务与管理",
    credits: 2,
    teacher: "陈老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.3,
    students: 2100,
    tags: ["英语基础", "跨学科融合", "小组报告", "随堂互动", "实操"],
    features: ["跨学科融合", "实操"],
    difficulty: "中等",
    assessment: "小组报告 + 随堂互动",
    intro: "外汇业务与管理围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含英语基础、跨学科融合、小组报告。",
    outline: ["外汇业务与管理基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "61",
    name: "国际金融风险管理",
    englishName: "国际金融风险管理",
    credits: 2,
    teacher: "王老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.8,
    students: 2237,
    tags: ["英语基础", "跨学科融合", "主修", "理论", "小组报告"],
    features: ["主修", "跨学科融合"],
    difficulty: "中等",
    assessment: "小组报告",
    intro: "国际金融风险管理围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含英语基础、跨学科融合、主修。",
    outline: ["国际金融风险管理基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "62",
    name: "金融数据分析与编程",
    englishName: "金融数据分析与编程",
    credits: 2,
    teacher: "李老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.3,
    students: 2374,
    tags: ["编程基础", "实操", "跨学科融合", "主修", "热"],
    features: ["热", "主修"],
    difficulty: "中等",
    assessment: "实操",
    intro: "金融数据分析与编程围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含编程基础、实操、跨学科融合。",
    outline: ["金融数据分析与编程基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "63",
    name: "金融数据挖掘",
    englishName: "金融数据挖掘",
    credits: 2,
    teacher: "周老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.8,
    students: 2511,
    tags: ["编程基础", "实操", "跨学科融合", "主修", "热"],
    features: ["热", "主修"],
    difficulty: "中等",
    assessment: "实操",
    intro: "金融数据挖掘围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含编程基础、实操、跨学科融合。",
    outline: ["金融数据挖掘基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "64",
    name: "区块链技术与应用",
    englishName: "区块链技术与应用",
    credits: 2,
    teacher: "赵老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.4,
    students: 2648,
    tags: ["编程基础", "实操", "跨学科融合", "主修", "热"],
    features: ["热", "主修"],
    difficulty: "中等",
    assessment: "实操",
    intro: "区块链技术与应用围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含编程基础、实操、跨学科融合。",
    outline: ["区块链技术与应用基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "65",
    name: "量化投资方法与应用",
    englishName: "量化投资方法与应用",
    credits: 2,
    teacher: "林老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.8,
    students: 2785,
    tags: ["编程基础", "实操", "跨学科融合", "金工基础", "难"],
    features: ["跨学科融合", "实操"],
    difficulty: "挑战",
    assessment: "实操",
    intro: "量化投资方法与应用围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含编程基础、实操、跨学科融合。",
    outline: ["量化投资方法与应用基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "66",
    name: "人工智能与金融应用",
    englishName: "人工智能与金融应用",
    credits: 2,
    teacher: "陈老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.4,
    students: 2922,
    tags: ["编程基础", "实操", "跨学科融合", "主修", "热"],
    features: ["热", "主修"],
    difficulty: "中等",
    assessment: "实操",
    intro: "人工智能与金融应用围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含编程基础、实操、跨学科融合。",
    outline: ["人工智能与金融应用基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "67",
    name: "大数据技术导论",
    englishName: "大数据技术导论",
    credits: 2,
    teacher: "王老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.9,
    students: 3059,
    tags: ["编程基础", "实操", "跨学科融合", "主修", "热"],
    features: ["热", "主修"],
    difficulty: "中等",
    assessment: "实操",
    intro: "大数据技术导论围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含编程基础、实操、跨学科融合。",
    outline: ["大数据技术导论基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "68",
    name: "公司财务案例",
    englishName: "公司财务案例",
    credits: 2,
    teacher: "李老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.9,
    students: 896,
    tags: ["小组报告", "随堂互动", "实操", "主修"],
    features: ["主修", "实操"],
    difficulty: "中等",
    assessment: "小组报告 + 随堂互动",
    intro: "公司财务案例围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含小组报告、随堂互动、实操。",
    outline: ["公司财务案例基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "69",
    name: "企业并购与重组",
    englishName: "企业并购与重组",
    credits: 2,
    teacher: "周老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.4,
    students: 1033,
    tags: ["小组报告", "随堂互动", "实操", "主修"],
    features: ["主修", "实操"],
    difficulty: "中等",
    assessment: "小组报告 + 随堂互动",
    intro: "企业并购与重组围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含小组报告、随堂互动、实操。",
    outline: ["企业并购与重组基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "70",
    name: "公司治理",
    englishName: "公司治理",
    credits: 2,
    teacher: "赵老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.0,
    students: 1170,
    tags: ["小组报告", "随堂互动", "实操", "论文", "主修"],
    features: ["主修", "实操"],
    difficulty: "中等",
    assessment: "小组报告 + 随堂互动",
    intro: "公司治理围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含小组报告、随堂互动、实操。",
    outline: ["公司治理基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "71",
    name: "资本运营",
    englishName: "资本运营",
    credits: 2,
    teacher: "林老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.5,
    students: 1307,
    tags: ["小组报告", "随堂互动", "实操", "主修"],
    features: ["主修", "实操"],
    difficulty: "中等",
    assessment: "小组报告 + 随堂互动",
    intro: "资本运营围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含小组报告、随堂互动、实操。",
    outline: ["资本运营基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
  {
    id: "72",
    name: "企业价值评估",
    englishName: "企业价值评估",
    credits: 2,
    teacher: "陈老师",
    college: "金融学院",
    category: "银行管理方向",
    rating: 4.0,
    students: 1444,
    tags: ["主修", "闭卷", "理论"],
    features: ["主修"],
    difficulty: "中等",
    assessment: "闭卷",
    intro: "企业价值评估围绕银行管理方向能力展开，适合结合职业目标进行选择。课程标签包含主修、闭卷、理论。",
    outline: ["企业价值评估基础框架", "核心概念与案例", "方法训练与课堂讨论", "综合应用与复盘"],
    cover: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=600",
    reviews: DEFAULT_REVIEWS
  },
];
export const SIMULATED_SCHEDULE = [
  { day: "周一", time: "08:30", room: "金融楼 204", courseId: "31" },
  { day: "周二", time: "10:10", room: "实验楼 302", courseId: "60" },
  { day: "周三", time: "14:00", room: "金融楼 108", courseId: "48" },
  { day: "周四", time: "15:40", room: "综合楼 501", courseId: "53" }
];
export const TAG_POOL = ["编程基础", "线代基础", "会计基础", "金工基础", "英语基础", "高数基础", "计量基础", "统计基础", "论文", "闭卷", "开卷", "小组报告", "随堂互动", "实操", "理论", "难", "热", "满", "高绩点", "主修", "跨学科融合"];
export const state = {
  alternateCourseIds: new Set<string>(),
  completedCourseIds: new Set<string>(),
  recommendationProfile: null as any,
  isLoggedIn: false,
  user: { name: "金融学学生", grade: "2023级", major: "金融学", avatar: "" }
};
